spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://capstone-design-db.cdmyweqqmmeq.ap-northeast-2.rds.amazonaws.com:3306/project_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wtgs9817
    password: asdf1193

  jpa:
    hibernate:
      ddl-auto: update  # create / update / validate / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: mail.hallym.ac.kr
    port: 25
    username: 20203305@hallym.ac.kr
    password: alstjr8578@   # 실제 이메일 비밀번호로 바꿔주세요
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: false  # 암호화 X (학교 설정 기준)


  logging:
    level:
      org.springframework.mail: DEBUG









